config:
  validation: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable', 'Test']

style:
  MaxLineLength:
    excludes: ['**/src/test/**', '**/src/androidTest/**']
  MagicNumber:
    ignoreAnnotated: ['Composable', 'Preview']
